name: flutter_application_test
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.5
  dio: ^5.8.0+1
  go_router: ^16.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.4
  pull_to_refresh: ^2.0.0
  flutter_swiper_view: ^1.1.6
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  # 可选：做图片缓存更顺滑
  cached_network_image: ^3.3.1
  # 富文本解析
  flutter_html: ^3.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
